### ISSUE TITLE
Link function not proving link id in Testing environment

### ISSUE THREAD

**Issue by abhishek316in** [BranchMetrics/web-branch-deep-linking#360] opened 2016-08-04 12:56 UTC
branch.link(data, function (err, link) {
      if (!err) {
             //got the link
       }
});

On calling this function I am suppose to get a link which redirects to my website with a parameter that is link id, something like this
https://myWebSite/?_branch_match_id=123456789
However all I am getting is:
https://myWebSite/

**Comment by jsaleigh** [comment] 2016-08-04 16:36
@abhishek316in Sorry you're having an issue here. The `_branch_match_id` shouldn't actually be appended until after a user clicks on the link that was passed into the callback.  There is an important point with this, that the link click will only append `_branch_match_id` one time.

However, I believe the link should have a path after your domain, returned in the callback to branch.link, so I need to be sure: is the link you get actually `https://myWebSite/` or is it something like `https://myWebSite/abcd/123xyz456m`?

**Comment by abhishek316in** [comment] 2016-08-05 05:52
Please note that I see this issue only when branch key which I pass during branch.init() is of **Test** environment. When I generate branch link I am getting link like **https://xxxx.app.link/sMggNvv7yv**, when I paste it on address bar and enter it, I get **https://myWebSite/**, however I expect URL like **https://myWebSite/?_branch_match_id=123456789**
This functionality works perfectly on **Live** environment
I don't get https://myWebSite/parameter1/parameter2.

**Comment by jsaleigh** [comment] 2016-08-05 17:56
Hi @abhishek316in. This is an interesting issue, but unfortunately I have not been able to reproduce it.  I'm following up with our Integrations team, who have a great deal of experience with finding and solving issues.  I'm leaving this issue open until we can find a resolve.

**Comment by aaustin** [comment] 2016-09-19 23:08
Hey @abhishek316in - We're unable to reproduce this ourselves, even with a test key. Can you please let us know if you're still encountering the issue? Closing the issue until then.

**Closed by aaustin** 2016-09-19 23:08 UTC
