### ISSUE TITLE
Global singleton prevents use of multiple keys

### ISSUE THREAD

**Issue by pho3nixf1re** [BranchMetrics/web-branch-deep-linking#525] opened 2017-10-13 18:55 UTC
Each call to init globally sets the app key. This means that there is no guarantee each instance of the Branch SDK is for a particular app. This makes the SDK unsafe to use for multiple apps. Is there an easy way to clone the imported SDK? Otherwise the init call should return an instance of the SDK that can standalone.

**Comment by rubinsingh** [comment] 2017-12-02 00:34
@pho3nixf1re could you please explain the issue further? If you've got 4 pages A, B, C and D, and include the Branch snippet found at the location below:

https://github.com/BranchMetrics/web-branch-deep-linking#quick-install

on those separate pages, then you should be able to initialize 4 separate apps on those pages through the branch.init() call given that you are not on a single page app.

**Comment by pho3nixf1re** [comment] 2017-12-13 02:26
I am using it within a server side rendered SPA so the api instance persists. The risk is low but it is a very unexpected way for a library to work. My expectation is that I create an instance that is self contained from other instances (eg. `new Branch(...configs)`). My solution for now was to re-init the Branch SDK on every submission and block the UI across all pages for each submission.

**Comment by csalmi-branch** [comment] 2019-01-26 00:45
@pho3nixf1re, the use of multiple keys is prevented by design. However we do have many customers with multiple products that they are marketing, and we are happy to help you get a setup that works for you. Would you be willing to file a ticket on support.branch.io if you are still experiencing issues with multiple keys?

Since this is by design, I'm closing this github issue. Please don't hesitate to reach out to us on support.branch.io or by opening a new github issue.

**Closed by csalmi-branch** 2019-01-26 00:45 UTC

**Comment by pho3nixf1re** [comment] 2019-01-28 15:31
So far it hasn't broken but we are currently ramping up traffic to our web apps. I'm fine with closing this for now as I took a hammer to it and forced it to work as I described above.
