### ISSUE TITLE
Import Module Error

### ISSUE THREAD

**Issue by JaredPon** [BranchMetrics/web-branch-deep-linking#352] opened 2016-07-18 20:11 UTC
I'm getting an error when I import the package into any file. The stack trace is posted below.  Any ideas on what might be causing this?

`import branch from 'branch-sdk';`

```
/Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:23
a(e):a(e))}},isEnabled:function(){return navigator.cookieEnabled}}}L.prototype.cookie=function(){return Ba(!1)};L.prototype.permcookie=function(){return Ba(!0)};L.prototype.pojo={getAll:function(){return this.j},get:function(b){return this.j[b]||null},set:function(b,a){this.j[b]=a},remove:function(b){delete this.j[b]},clear:function(){this.j={}},isEnabled:function(){return!0}};function Ca(){}Ca.prototype.f=0;function Da(b,a,c){if("undefined"===typeof a)return"";var d=[];if(a instanceof Array){for(b=0;b<a.length;b++)d.push(encodeURIComponent(c)+"="+encodeURIComponent(a[b]));return d.join("&")}for(var e in a)a.hasOwnProperty(e)&&(a[e]instanceof Array||"object"===typeof a[e]?d.push(Da(b,a[e],c?c+"."+e:e)):d.push(encodeURIComponent(c?c+"."+e:e)+"="+encodeURIComponent(a[e])));return d.join("&")}
                                         ^

ReferenceError: navigator is not defined
    at Object.Ba.isEnabled (/Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:23:42)
    at new L (/Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:18:742)
    at new V (/Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:65:179)
    at /Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:85:314
    at Object.<anonymous> (/Users/jared/Development/autolotto/backend/node_modules/branch-sdk/dist/build.min.js:85:592)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jared/Development/autolotto/backend/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by jsaleigh** [comment] 2016-07-18 20:21
Hi @JaredPon! The issue is in using the Web SDK in backend code, where the global object doesn't have a Navigator object the way that a Window global would.

We're going to add some code to help in this case, but I believe what you could use is the HTTP API.  The reference for that can be found here: https://dev.branch.io/methods-endpoints/

**Comment by zeeshabnc** [comment] 2016-09-20 04:01
Closing this issue out for now, @JaredPon feel free to open if you are still running into issues.

**Closed by zeeshabnc** 2016-09-20 04:01 UTC
