### ISSUE TITLE
showWindowsPhone:false missing Nokia phone UA

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/web-branch-deep-linking#380] opened 2016-09-19 21:07 UTC
Using the following option: `"showWindowsPhone: false"`, still misses a key Nokia Windows Phone with the following User Agent string:
`Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 730 Dual SIM) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537`

**Comment by jsaleigh** [comment] 2016-10-03 16:56
Note that the issue is that `utils.mobileUserAgent` in 1_utils.js sees this as an Android phone, and does no further checks after that.

**Comment by zeeshabnc** [comment] 2016-11-19 00:31
Closing this out and tracked internally on JIRA.

**Closed by zeeshabnc** 2016-11-19 00:31 UTC
